2. JS-Data-Types. Sort, Pick, Omit.
js-tasks-ru/js-20210309-2_y-dubovitsky pull request #6
Opened 2021-03-12 18:58 UTC by y-dubovitsky

Решение задач по теме 'Основы JS. Примитивные типы данных'.

2021-03-12 18:58 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-03-14 14:18 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return param === 'asc' ? result : result.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-03-14 14:19 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const collator = new Intl.Collator(
какая есть альтернатива `Intl.Collator`?

2021-03-14 14:20 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let result = {};
объявлять переменную через `let` присваивать в нее пустой объект, а потом переприсваивать новое значение - так делать не следует.
Лучше сделать вот так:
```
const result = Object.fromEntries(...
```

2021-03-14 14:21 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    let result = {};
аналогичное замечание как в решении `pick`

2021-03-14 14:21 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-03-19 20:20 UTC, y-dubovitsky commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return param === 'asc' ? result : result.reverse();
Убрал reverse и добавил множитель в компаратору в зависимости от направления сортировки.

2021-03-19 20:22 UTC, y-dubovitsky commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const collator = new Intl.Collator(
Intl.Collator не стал убирать, а добавил дополнительную функцию, которая использует встроенный метод объекта String, а именно 

> str.localeCompare(compareString[, locales[, options]])

2021-03-19 20:22 UTC, y-dubovitsky commented on 02-javascript-data-types/2-pick/index.js
> +    let result = {};
Поправил.

2021-03-19 20:22 UTC, y-dubovitsky commented on 02-javascript-data-types/3-omit/index.js
> +    let result = {};
Тоже поправил.

2021-03-22 10:18 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const collator = new Intl.Collator(
`Intl.Collator` - это хорошее решение, конечно убирать его не нужно.
`localeCompare` - это альтернатива

2021-03-22 10:18 UTC, dosandk approved these changes

2021-03-22 10:19 UTC, merged